---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8880, host: 8880}]

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-7.1
#  - name: opensuse-13.2
#    driver:
#      box: opensuse-13.2
#      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.2-x86_64_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[yourls-cookbook::default]
    attributes:
